# Generated by Django 3.2.5 on 2022-10-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requester',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='requester',
            name='travel_medium',
        ),
        migrations.AddField(
            model_name='requester',
            name='asset_type',
            field=models.IntegerField(default=0),
        ),
    ]
