# Generated by Django 3.2.5 on 2022-10-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20221019_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
