# Generated by Django 3.2.5 on 2022-10-20 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_requester_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riders',
            name='travel_medium',
            field=models.IntegerField(default=0),
        ),
    ]
