# Generated by Django 3.2.5 on 2022-10-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_riders_travel_medium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riders',
            name='rider_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='riders',
            name='rider_phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
