# Generated by Django 3.2.5 on 2022-10-20 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20221020_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='requester',
            name='assigned_rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='polls.riders'),
        ),
    ]
